### ISSUE TITLE
support for nested fields?

### ISSUE THREAD

**Issue by dustin-decker** [caibirdme/yql#1]
Is there support for querying on nested fields?

Given this sample:

```json
{  
   "src_ip":"127.0.0.1",
   "event":{  
      "Event":{  
         "Process":{  
            "type":2,
            "exec_filename":"/usr/bin/dig",
            "exec_command_line":[  
               "dig",
               "+short",
               "ifjeow0234f90iwefo2odj.wat.lol"
            ]
         }
      }
   }
}
```

Can I do something like these queries using this library?
`event.Event.Process.exec_filename='/usr/bin/dig' and src_ip='127.0.0.1'`

How about querying a nested array?
`src_ip='127.0.0.1' and 'ifjeow0234f90iwefo2odj.wat.lol' in event.Event.Process.exec_command_line`

**Comment by caibirdme** [comment]
> Can I do something like these queries using this library?
event.Event.Rules.exec_filename='/usr/bin/dig' and src_ip='127.0.0.1'

Yes

> How about querying a nested array?
src_ip='127.0.0.1' and 'ifjeow0234f90iwefo2odj.wat.lol' in event.Event.Rules.exec_command_line

No, the grammar is the same as sql, so `in (a1,a2)` is the only legal grammar

**Comment by sdghchj** [comment]
> > Can I do something like these queries using this library?
> > event.Event.Rules.exec_filename='/usr/bin/dig' and src_ip='127.0.0.1'
> 
> Yes

not support actually , via my testing
