### ISSUE TITLE
关于*_test.go的几个问题

### ISSUE THREAD

**Issue by luciferofwg** [caibirdme/yql#4]
版主，你好！
在学习你的代码的过程中，发现几个问题，想请教一下。
在文件 yql_test.go 中引用yql包中的部分接口函数时，并没有使用yql.Match 并且 使用的常量 epsilon 也是不能直接引用的，不知道是我这边环境的问题还是代码问题？

**Comment by caibirdme** [comment]
因为我的yql_test.go也是package yql，是同一个包，因此可以使用包中的私有变量

**Comment by luciferofwg** [comment]
嗯，谢谢~
我在使用Match匹配规则时，传入的参数中包含有map，那么规则应该怎么写呢，我尝试的写了一下，似乎不是我预期的值，正在学习你的源码，限于刚接触不久的golang，水平着实有限，肯请指教~谢谢！以下是我添加的部分代码
`rawYQL = `score in (7,1,9,5,3) and hobby.key in ('soccer', 'swim')`
	m := map[string]string{"key":"soccer"}
	result, _ = yql.Match(rawYQL, map[string]interface{}{
		"score": []int64{3, 5, 1},
		"hobby": m,
	})
	fmt.Println(result)`

**Comment by caibirdme** [comment]
@luciferofwg 以上语法是不支持 hobby.key这种变量访问方式，目前只支持和sql一样直接引用变量名。你上面的例子应该改写为：
```
rawYQL = score in (7,1,9,5,3) and hobby_key in ('soccer', 'swim')
result, _ = yql.Match(rawYQL, map[string]interface{}{ "score": []int64{3, 5, 1}, "hobby": m["key"], })
```

**Comment by caibirdme** [comment]
只有lambda表达式中才支持a.b这样的语法

**Comment by luciferofwg** [comment]
> 只有lambda表达式中才支持a.b这样的语法

嗯，谢谢版主~

**Comment by sdghchj** [comment]
> @luciferofwg 以上语法是不支持 hobby.key这种变量访问方式，目前只支持和sql一样直接引用变量名。你上面的例子应该改写为：
> 
> ```
> rawYQL = score in (7,1,9,5,3) and hobby_key in ('soccer', 'swim')
> result, _ = yql.Match(rawYQL, map[string]interface{}{ "score": []int64{3, 5, 1}, "hobby_key": m["key"], })
> ```

不支持？
4 Jun 2018:  https://github.com/caibirdme/yql/issues/1#issuecomment-394214549
到底支持还是不支持？

**Comment by caibirdme** [comment]
@sdghchj YQL有两部分，一部分是sql，这部分不支持nested object。另一部分是lambda，这部分是支持的
